version: '3'

services:
  orderservice:
    container_name: orderservice
    build:
      context: ../
      dockerfile: docker/Dockerfile.orderservice
    env_file:
      - ../.env
    ports:
      - ${ORDER_PORT}:${ORDER_PORT}
    depends_on:
      - orderservice_db
      - storegrpcservice

  orderservice_db:
    image: mysql:8.0
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', "--init-connect='SET NAMES utf8mb4;'"]
    container_name: orderservice_db
    restart: always
    env_file:
      - ../.env
    environment:
      MYSQL_DATABASE: ${ORDER_DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${ORDER_DATABASE_PASSWORD}
    ports:
      - 3370:3306
    volumes:
      - ../../var/orderservice/database:/var/lib/mysql